# This is a basic workflow to help you get started with Actions

name: 'Github Actions Weather Bot'

# Controls when the workflow will run
on:

  schedule:
    - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout actions
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
      - uses: actions/setup-python@v1
        with:
         python-version: 3.7

      # Runs a set of commands using the runners shell
      - name: Run a py
        run: |
          cd whether
          python main.py
          
